---
title: "R Notebook"
output: html_notebook
---

```{r Setup, include = F}
knitr::opts_chunk$set(include = F)
```

```{r Packages}
library(dplyr)
library(tidyr)
library(readr)
library(magrittr)
library(ggplot2)
library(pander)
library(ppcor)
library(car)
library(ggpubr)
library(gridExtra)
library(cowplot)
library(patchwork)
library(conflicted)
library(QuantPsyc)
library(MeMoBootR)
library(epitools)
library(stringr)
#library(png)
```

```{r SETUP clean-up, eval=T}
# remove all objects to start with clean environment
rm(list=ls())
```

```{r SETUP solve function conflicts}
conflicts_prefer(dplyr::filter, dplyr::select, dplyr::n())
```

```{r Functions}
t.report <- function(tt){
  tvalue <- tt$statistic %>% formatC(digits = 2, format = "f")
  pvalue <- tt$p.value %>% formatC(digits = 2, format = "f")
  if (round(tt$parameter, 0) == tt$parameter) {
    df <- tt$parameter
  } else {
    df <- formatC(digits = 2, format = "f")
  }
  if (tt$p.value < 0.0005) {
    pvalue <- " < 0.001" 
  } else { 
    if (tt$p.value < 0.005) {
      pvalue <- paste0(" = ",tt$p.value %>% formatC(digits = 3, format = "f"))
    } else {
      pvalue <- paste0(" = ",tt$p.value %>% formatC(digits = 2, format = "f"))
    }
    } 
  paste0("*t*(",df,") = ",tvalue, ", *p*", pvalue)
}

mean_sd_se.report <- function(df, filtervar, filter, var){
  mean <- df %>% filter (!!filtervar == filter) %>% .[[var]] %>% mean() %>% round(2)
  sd <- df %>% filter (!!filtervar == filter) %>% .[[var]] %>% sd() %>% round(2)
  se <- df %>% filter (!!filtervar == filter) %>% .[[var]] %>% se() %>% round(2)
  
  paste0(filter," mean = ", mean, ", sd = ", sd, ", ", "se = ", se)
}

remove_outliers <- function(data, variables, multiplier = 2) {
  for (variable in variables) {
    Q1 <- quantile(data[[variable]], 0.25, na.rm = TRUE)
    Q3 <- quantile(data[[variable]], 0.75, na.rm = TRUE)
    IQR <- Q3 - Q1
    lower_bound <- Q1 - multiplier * IQR
    upper_bound <- Q3 + multiplier * IQR

    data <- data %>%
      filter(get(variable) >= lower_bound & get(variable) <= upper_bound)
  }
  
  return(data)
}
```

```{r DATA loading}
GWASs_list <- read.delim("~/Projects/hitkip_allelic_load_exp_risk/data/gwas/GWASs_list.tsv")
```
```{r ANALYSIS}
ukb_gwas <-
GWASs_list %>% 
  filter(str_detect(title, "Exome sequ")) %>% 
  select(study_id,efo_trait, reported_trait, title, initial_sample, publication_date, snp_count) %>% 
  mutate(publication_date = as.Date(publication_date, format = "%Y-%m-%d")) %>% 
  arrange(efo_trait, title, publication_date)
```

```{r SAVE data}
write.table(ukb_gwas, file = "data/gwas/ukb_gwas_selection.tsv", sep = "\t", row.names = TRUE, quote = FALSE)
```


